image: Visual Studio 2015
version: 0.0.1.{build}
environment:
  MYGET_FEED: 'https://www.myget.org/F/kai2nenobu'
  MYGET_API_KEY:
    secure: yYHBdK/0WBIzCZ89/ux8dw==
  MINGW_32BIT: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32'
  MINGW_64BIT: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64'
install:
  - dir
build_script:
  # a5m2
  - choco pack %APPVEYOR_BUILD_FOLDER%\a5m2\a5m2.nuspec
  # cpdf-cr
  - choco pack %APPVEYOR_BUILD_FOLDER%\cpdf-cr\cpdf-cr.nuspec
  # check build artifacts
  - dir
test_script:
  - '%APPVEYOR_BUILD_FOLDER%\a5m2\test.bat'
  - '%APPVEYOR_BUILD_FOLDER%\cpdf-cr\test.bat'
deploy_script:
  - dir
  - ps: choco push a5m2.2.12.2.nupkg --source "$env:MYGET_FEED%" -k="$env:yYHBdK/0WBIzCZ89/ux8dw=="
artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
build:
  verbosity: detailed
