image: Visual Studio 2015
version: 0.0.1.{build}

branches:
  only:
    - /package\/.*/

environment:
  MYGET_FEED: 'https://www.myget.org/F/kai2nenobu'
  MYGET_API_KEY:
    secure: Y/8UFTPxim7reHigg7iClTv5cu1QI4yA+zPs4DelBkFyMlUZxkzppJGkijKUuRVZ
  MINGW_32BIT: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32'
  MINGW_64BIT: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64'
before_build:
  - cmd: |
      for /f "tokens=1-2 delims=/" %%a in ("%APPVEYOR_REPO_BRANCH%") do (
          set PREFIX=%%a
          set PACKAGE_ID=%%b
      )
  - echo %PREFIX%
  - echo %PACKAGE_ID%
  - exit /b 1
build_script:
  # a5m2
  - choco pack %APPVEYOR_BUILD_FOLDER%\a5m2\a5m2.nuspec
  # cpdf-cr
  - choco pack %APPVEYOR_BUILD_FOLDER%\cpdf-cr\cpdf-cr.nuspec
  # check build artifacts
  - dir
test_script:
  - '%APPVEYOR_BUILD_FOLDER%\a5m2\test.bat'
  - '%APPVEYOR_BUILD_FOLDER%\cpdf-cr\test.bat'
deploy_script:
  - dir
  - for %%p in (*.nupkg) do choco push %%p -s "%MYGET_FEED%" -k "%MYGET_API_KEY%"
artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: Xy6BVJYVnM0lJ0eD9Uw8z1XSEFErqUbRozlhX7gmoAWDUJ2VfDgH3JId4mAOkz3vZ6wlQenfCc2Lyotvf0ABfZygpjB0qYD++2Pl/HsRLPw=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
build:
  verbosity: detailed
