image: Visual Studio 2015
version: 0.0.1.{build}

branches:
  only:
    - /package\/.*/

environment:
  MYGET_FEED: 'https://www.myget.org/F/kai2nenobu'
  MYGET_API_KEY:
    secure: Y/8UFTPxim7reHigg7iClTv5cu1QI4yA+zPs4DelBkFyMlUZxkzppJGkijKUuRVZ
  MINGW_32BIT: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32'
  MINGW_64BIT: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64'
before_build:
  # Detect a target package from a branch name
  - ps: |
      $array = $env:APPVEYOR_REPO_BRANCH -split '/'
      $env:PREFIX = $array[0]
      $env:PACKAGE_ID = $array[1]
build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\%PACKAGE_ID%"
  # Packaging
  - for /f "tokens=* usebackq" %%v in (`type VERSION`) do choco pack --version %%v
  - dir
test_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\%PACKAGE_ID%"
  - if exist test.bat .\test.bat
deploy_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\%PACKAGE_ID%"
  - choco push -s "%MYGET_FEED%" -k "%MYGET_API_KEY%"
artifacts:
  # pushing all *.nupkg files in build directory recursively
  - path: '**\*.nupkg'
notifications:
  - provider: Slack
    incoming_webhook:
      secure: Xy6BVJYVnM0lJ0eD9Uw8z1XSEFErqUbRozlhX7gmoAWDUJ2VfDgH3JId4mAOkz3vZ6wlQenfCc2Lyotvf0ABfZygpjB0qYD++2Pl/HsRLPw=
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: false
build:
  verbosity: detailed
