image: Visual Studio 2015
version: 0.0.1.{build}
environment:
  MINGW_32BIT: 'C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\mingw32'
  MINGW_64BIT: 'C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64'
install:
  - dir
build_script:
  # a5m2
  - cd %APPVEYOR_BUILD_FOLDER%\a5m2
  - choco pack
  # cpdf-cr
  - cd %APPVEYOR_BUILD_FOLDER%\cpdf-cr
  - choco pack
  - test.bat
  # check build artifacts
  - cd %APPVEYOR_BUILD_FOLDER%
  - dir a5m2 cpdf-cr
build:
  verbosity: detailed
